# for the leaderboard service. We use Redis because Sorted
# Sets provide efficient operations for maintaining a leaderboard,

version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: leaderboard-redis #container for easier identify
    ports:
      - "6379:6379" #Redis on the default port
    volumes:
      - redis-data:/data. 
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis-data: